<div class="container">
    <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4">
            <div ng-controller="Auth" class="account-wall">
                <div id="my-tab-content" class="tab-content">
                    <div class="tab-pane active" id="login">
                        <img class="profile-img" src="imgs/asu_501_img.png" />

                        <form class="form-signin" action=""  method="">
                            <input type="text" class="form-control"  ng-model="username" placeholder="Usuário" required autofocus>
                            <input type="password" ng-model="passwordlogin" class="form-control" placeholder="Senha" required>
                            <input type="submit" ng-click="actAuth()" class="btn btn-lg btn-default btn-block" value="Entrar" />
                        </form>
                        <div id="tabs" data-tabs="tabs">
                            <p class="text-center"><a href="#register" data-toggle="tab">Solicitar Registro</a></p>
                        </div>
                    </div>
                    <div class="tab-pane" id="register">
                        <img class="profile-img" src="imgs/asu_501_img.png" />
                        <form class="form-signin" action="" method="">
                            <input type="text" ng-model="name" class="form-control" placeholder="Nome Completo" required autofocus>
                            <input type="email"  ng-model="email" class="form-control" placeholder="Email" required>
                            <input type="password" ng-model="password" class="form-control" placeholder="Senha" required>
                            <input type="submit" ng-click="actRegister()"  class="btn btn-lg btn-default btn-block" value="Registrar" />
                        </form>
                        <div id="tabs" data-tabs="tabs">
                            <p class="text-center"><a  href="#login" id="loginScreen" data-toggle="tab">Efetuar Login</a></p>
                        </div>
                    </div>

                    <div class="tab-pane" id="user1">
                        <img class="profile-img" src="https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=120"
                             alt="">
                        <h3 class="text-center">User Name 1</h3>
                        <form class="form-signin" action="" method="">
                            <input type="hidden" class="form-control" value="User Name">
                            <input type="password" class="form-control" placeholder="Password" autofocus required>
                            <input type="submit" class="btn btn-lg btn-default btn-block" value="Sign In" />
                        </form>

                    </div>
                    <div class="tab-pane" id="user2">
                        <img class="profile-img" src="https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=120"
                             alt="">
                        <h3 class="text-center">User Name 2</h3>
                        <form class="form-signin" action="" method="">
                            <input type="hidden" class="form-control" value="User Name">
                            <input type="password" class="form-control" placeholder="Password" autofocus required>
                            <input type="submit" class="btn btn-lg btn-default btn-block" value="Sign In" />
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>