

<div ng-controller="Home" ng-show="visible" class="container">
    <div class="col-md-4">
        <div class="alert alert-success">
            <div class="panel-body">
                <img src="https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xpa1/v/t1.0-1/c3.0.100.100/p100x100/1176410_641202149304196_134362683595865223_n.jpg?oh=2f08e0b97dcb230c1156edf125d10e31&oe=549C63E6&__gda__=1419657514_746df46625c05b91543a4208db9e06bc" class="pic_ina img-thumbnail"/>
                <div class="con_ina">
                    <b> Ajith jojo </b><br>
                    Thank you for using this snipp
                    <br> Add me as a frnd on facebook . i will accept all requests
                </div>
            </div>
            <a href="https://www.facebook.com/ajithjojo999" target="blank"><button type="button" class="btn btn-success btn-xs btn_inr">Go to my fb  </button></a>
        </div>
    </div>
</div>