<html>
 <head>
 <title>Tutorial de HTML5</title>
 <meta name="description" content="Como usar as tags header, footer e article em HTML5" />
 <meta charset="utf-8" />
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" />
 <link rel="stylesheet" href="assets/stylesheet.css" />
 <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.1/angular.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>

 <script type="text/javascript">

 </script>
</head>
<body>
<?php $this->content() ?>
</body>
</html>
