-- MySQL Script generated by MySQL Workbench
-- 01/26/17 12:37:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema eadline
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eadline
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eadline` DEFAULT CHARACTER SET utf8 ;
USE `eadline` ;

-- -----------------------------------------------------
-- Table `eadline`.`levelusers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eadline`.`levelusers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `typeUser` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eadline`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eadline`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `sirname` VARCHAR(45) NULL,
  `lastoken` TEXT NULL,
  `levelusers_id` INT NOT NULL,
  `ativo` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_levelusers_idx` (`levelusers_id` ASC),
  CONSTRAINT `fk_users_levelusers`
    FOREIGN KEY (`levelusers_id`)
    REFERENCES `eadline`.`levelusers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
