-- MySQL Script generated by MySQL Workbench
-- Dom 29 Jan 2017 18:58:26 BRST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema eadline
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eadline
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eadline` DEFAULT CHARACTER SET utf8 ;
USE `eadline` ;

-- -----------------------------------------------------
-- Table `eadline`.`levelusers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eadline`.`levelusers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `typeUser` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eadline`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eadline`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(200) NULL DEFAULT NULL,
  `hashsalt` VARCHAR(128) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `lastoken` TEXT NULL DEFAULT NULL,
  `levelusers_id` INT(11) NOT NULL,
  `ativo` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_levelusers_idx` (`levelusers_id` ASC),
  CONSTRAINT `fk_users_levelusers`
    FOREIGN KEY (`levelusers_id`)
    REFERENCES `eadline`.`levelusers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eadline`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eadline`.`courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `namecourse` VARCHAR(45) NULL,
  `public` VARCHAR(45) NULL,
  `type_course` VARCHAR(45) NULL COMMENT 'Public or private course',
  `users_id` INT(11) NOT NULL,
  `sumary` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_courses_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_courses_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `eadline`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eadline`.`topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eadline`.`topics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(200) NULL,
  `source_video` VARCHAR(200) NULL,
  `courses_id` INT NOT NULL,
  `number_order` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_topics_courses1_idx` (`courses_id` ASC),
  CONSTRAINT `fk_topics_courses1`
    FOREIGN KEY (`courses_id`)
    REFERENCES `eadline`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eadline`.`didatic_material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eadline`.`didatic_material` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `source_material` VARCHAR(200) NULL,
  `title_material` VARCHAR(45) NULL,
  `topics_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_didatic_material_topics1_idx` (`topics_id` ASC),
  CONSTRAINT `fk_didatic_material_topics1`
    FOREIGN KEY (`topics_id`)
    REFERENCES `eadline`.`topics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
